version: "3"

services:
  web:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
